AY2324S2-CS2103T-F11-4/tp

- src/main/java/seedu/address/model/util/SampleDataUtil.java
Just some minor fix in the sample data to adapt the latest room number format.
> Change room number format in sample data

- docs/diagrams/Dormie.puml
- docs/diagrams/ModelClassDiagram.puml
UML:
ModelClassDiagram
-Class Dorm
-Person *--> "0..1" Dorm
Dormie.puml
-dorm: Dorm
> Add Dorm to UML

- docs/DeveloperGuide.md
- src/main/java/seedu/address/logic/commands/AddCommand.java
Update DG with free time tag implementation
Update the format of the free time tag in the text that appears when there is invalid input for add command
> Update DG and message usage

- src/main/java/seedu/address/model/person/Birthday.java
- src/test/java/seedu/address/model/person/BirthdayTest.java
Bugs fixed
* Invalid dates such as "30-02-2024" can no longer pass the validation test
* Date that comes after the current date can no longer pass the validation test
> Fix birthday bug

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AddTimeCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddTimeCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/test/java/seedu/address/logic/commands/AddTimeCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddTimeCommandParserTest.java
- src/test/java/seedu/address/testutil/EditPersonFreeTimeDescriptorBuilder.java
> Add AddFreeTime command

- src/main/java/seedu/address/logic/commands/FindByNameCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/FindFreePersonCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FindByNameCommandParser.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/FindFreePersonCommandParser.java
- src/main/java/seedu/address/model/person/PersonIsFreePredicate.java
- src/main/java/seedu/address/model/tag/FreeTimeTag.java
- src/test/java/seedu/address/logic/commands/FindByNameCommandTest.java
- src/test/java/seedu/address/logic/commands/FindFreePersonCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindByNameCommandParserTest.java
- src/test/java/seedu/address/logic/parser/FindFreePersonCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonIsFreePredicateTest.java
- src/test/java/seedu/address/model/tag/FreeTimeTagTest.java
Closes #68
* Turned `FindCommand` into an abstract class
* Added two classes `FindByNameCommand` and `FindFreePersonCommand`
* Modified `AddressBookParser` to support `whoisfree` command
* Turned `FindCommandParser` into an abstract class
* Added two classes `FindByNameCommandParser` and `FindFreePersonCommandParser`
* Created new classes `PersonIsFreePredicate` to be used when filtering the person list
* Added a method to `FreeTimeTag` to check if the input time is included in the current tag
* Added test cases
Use case of the command `whoisfree Mon:0700`
> View person by free time

- src/main/java/seedu/address/logic/parser/AddCommandParser.java
> Add no duplicate prefix check for birthday and dormtag

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/model/person/PersonTest.java
Description for changes are written above each changed file as comments.
Closes #112
> Minor flaw fix; Disable duplicate for phone, name, telegram; Enable duplicate for name

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddCommand.java
Some parts that have the trace of address book are changed to Dormie
> Edit add command part in feature

- src/main/java/seedu/address/model/person/RoomNumber.java
> Specify the proper room number format more precisely

- docs/UserGuide.md
- src/main/java/seedu/address/model/person/Phone.java
> Change phone field specification

- docs/UserGuide.md
- docs/index.md
Fixed bugs and added acknowledgements for code reuse
- Properly define valid input for name 
- #219 #203
- Properly define valid input for dorm tags 
- #218
- Behaviour of Find Feature does not match expected behaviour 
- #183 #173
- Find Command has vague or problematic phrasing: Command syntax KEYWORD is vague 
- #177
> Fix bugs in UG

- docs/UserGuide.md
- docs/team/justweihao.md
Add PPP and explanation on `whoisfree` command
> Fix UG and update PPP

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddTimeCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
- src/test/java/seedu/address/logic/commands/AddTimeCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteTimeCommandTest.java
Closes issue #187.
User will receive "No matching free time to be deleted for the chosen person." if:
1. The chosen person has no free time.
2. None of the chosen person's free time matches the specified free times (actually includes the first point).
> Fix error message for addTime and deleteTime

- docs/site.json
There is an "AddressBook Level-3" in the title
> Remove suffix from site.json

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddTimeCommand.java
- src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/tag/FreeTimeTag.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Grouped parts that do similar things into a function. The code behaviour should be entirely unchanged.
> Code refactor

- docs/DeveloperGuide.md
- docs/index.md
Updated:
- acknowledgements (for my reuse code)
- target profile
- value proposition
- user stories
- use cases
- NFR
> Update user stories

- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Birthday.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/model/person/BirthdayTest.java
Fix #189 
Fix #216
Fix #147
Changes:
- Added error message for invalid date value
- Added error message for a future date
Effect of changes: Error message now varies based on the violation instead of saying incorrect format
> Fix birthday error message

- docs/DeveloperGuide.md
- docs/UserGuide.md
Removed the 11th planned enhancement from the DG as well
> Update whoisfree and other minor typos

- src/main/java/seedu/address/logic/commands/EditCommand.java
> Fix edit bug
